#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyLinhKien")]
	public partial class DataQuanLyLinhKienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertPhieuNhapKho(PhieuNhapKho instance);
    partial void UpdatePhieuNhapKho(PhieuNhapKho instance);
    partial void DeletePhieuNhapKho(PhieuNhapKho instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertLoaiNhanVien(LoaiNhanVien instance);
    partial void UpdateLoaiNhanVien(LoaiNhanVien instance);
    partial void DeleteLoaiNhanVien(LoaiNhanVien instance);
    partial void InsertNhaCungCap(NhaCungCap instance);
    partial void UpdateNhaCungCap(NhaCungCap instance);
    partial void DeleteNhaCungCap(NhaCungCap instance);
    partial void InsertLoaiLinhKien(LoaiLinhKien instance);
    partial void UpdateLoaiLinhKien(LoaiLinhKien instance);
    partial void DeleteLoaiLinhKien(LoaiLinhKien instance);
    partial void InsertLinhkien(Linhkien instance);
    partial void UpdateLinhkien(Linhkien instance);
    partial void DeleteLinhkien(Linhkien instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDonDatHang(DonDatHang instance);
    partial void UpdateDonDatHang(DonDatHang instance);
    partial void DeleteDonDatHang(DonDatHang instance);
    partial void InsertChiTietPhieuNhapKho(ChiTietPhieuNhapKho instance);
    partial void UpdateChiTietPhieuNhapKho(ChiTietPhieuNhapKho instance);
    partial void DeleteChiTietPhieuNhapKho(ChiTietPhieuNhapKho instance);
    partial void InsertChiTietDonDatHang(ChiTietDonDatHang instance);
    partial void UpdateChiTietDonDatHang(ChiTietDonDatHang instance);
    partial void DeleteChiTietDonDatHang(ChiTietDonDatHang instance);
    #endregion
		
		public DataQuanLyLinhKienDataContext() : 
				base(global::DAL.Properties.Settings.Default.QuanLyLinhKienConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<PhieuNhapKho> PhieuNhapKhos
		{
			get
			{
				return this.GetTable<PhieuNhapKho>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<LoaiNhanVien> LoaiNhanViens
		{
			get
			{
				return this.GetTable<LoaiNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhaCungCap> NhaCungCaps
		{
			get
			{
				return this.GetTable<NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<LoaiLinhKien> LoaiLinhKiens
		{
			get
			{
				return this.GetTable<LoaiLinhKien>();
			}
		}
		
		public System.Data.Linq.Table<Linhkien> Linhkiens
		{
			get
			{
				return this.GetTable<Linhkien>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DonDatHang> DonDatHangs
		{
			get
			{
				return this.GetTable<DonDatHang>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhos
		{
			get
			{
				return this.GetTable<ChiTietPhieuNhapKho>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietDonDatHang> ChiTietDonDatHangs
		{
			get
			{
				return this.GetTable<ChiTietDonDatHang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maTaiKhoan;
		
		private string _matKhau;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaTaiKhoanChanging(string value);
    partial void OnmaTaiKhoanChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maTaiKhoan", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maTaiKhoan
		{
			get
			{
				return this._maTaiKhoan;
			}
			set
			{
				if ((this._maTaiKhoan != value))
				{
					this.OnmaTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._maTaiKhoan = value;
					this.SendPropertyChanged("maTaiKhoan");
					this.OnmaTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_NhanVien", ThisKey="maTaiKhoan", OtherKey="maNhanVien", IsUnique=true, IsForeignKey=false)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.TaiKhoan = null;
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan = this;
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_KhachHang", Storage="_KhachHang", ThisKey="maTaiKhoan", OtherKey="maKhachHang", IsUnique=true, IsForeignKey=false)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.TaiKhoan = null;
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan = this;
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuNhapKho")]
	public partial class PhieuNhapKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhieuNhapKho;
		
		private string _maNhaCungCap;
		
		private string _maNhanVienThuKho;
		
		private string _maNhanVienKeToanKho;
		
		private System.DateTime _ngayLap;
		
		private double _tongTien;
		
		private string _trangThai;
		
		private EntitySet<ChiTietPhieuNhapKho> _ChiTietPhieuNhapKhos;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<NhanVien> _NhanVien1;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhieuNhapKhoChanging(string value);
    partial void OnmaPhieuNhapKhoChanged();
    partial void OnmaNhaCungCapChanging(string value);
    partial void OnmaNhaCungCapChanged();
    partial void OnmaNhanVienThuKhoChanging(string value);
    partial void OnmaNhanVienThuKhoChanged();
    partial void OnmaNhanVienKeToanKhoChanging(string value);
    partial void OnmaNhanVienKeToanKhoChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    partial void OntongTienChanging(double value);
    partial void OntongTienChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public PhieuNhapKho()
		{
			this._ChiTietPhieuNhapKhos = new EntitySet<ChiTietPhieuNhapKho>(new Action<ChiTietPhieuNhapKho>(this.attach_ChiTietPhieuNhapKhos), new Action<ChiTietPhieuNhapKho>(this.detach_ChiTietPhieuNhapKhos));
			this._NhanVien = default(EntityRef<NhanVien>);
			this._NhanVien1 = default(EntityRef<NhanVien>);
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieuNhapKho", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhieuNhapKho
		{
			get
			{
				return this._maPhieuNhapKho;
			}
			set
			{
				if ((this._maPhieuNhapKho != value))
				{
					this.OnmaPhieuNhapKhoChanging(value);
					this.SendPropertyChanging();
					this._maPhieuNhapKho = value;
					this.SendPropertyChanged("maPhieuNhapKho");
					this.OnmaPhieuNhapKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhaCungCap", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maNhaCungCap
		{
			get
			{
				return this._maNhaCungCap;
			}
			set
			{
				if ((this._maNhaCungCap != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._maNhaCungCap = value;
					this.SendPropertyChanged("maNhaCungCap");
					this.OnmaNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVienThuKho", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maNhanVienThuKho
		{
			get
			{
				return this._maNhanVienThuKho;
			}
			set
			{
				if ((this._maNhanVienThuKho != value))
				{
					if (this._NhanVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienThuKhoChanging(value);
					this.SendPropertyChanging();
					this._maNhanVienThuKho = value;
					this.SendPropertyChanged("maNhanVienThuKho");
					this.OnmaNhanVienThuKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVienKeToanKho", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maNhanVienKeToanKho
		{
			get
			{
				return this._maNhanVienKeToanKho;
			}
			set
			{
				if ((this._maNhanVienKeToanKho != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienKeToanKhoChanging(value);
					this.SendPropertyChanging();
					this._maNhanVienKeToanKho = value;
					this.SendPropertyChanged("maNhanVienKeToanKho");
					this.OnmaNhanVienKeToanKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="Date NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Float NOT NULL")]
		public double tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhapKho_ChiTietPhieuNhapKho", Storage="_ChiTietPhieuNhapKhos", ThisKey="maPhieuNhapKho", OtherKey="maPhieuNhapKho")]
		public EntitySet<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhos
		{
			get
			{
				return this._ChiTietPhieuNhapKhos;
			}
			set
			{
				this._ChiTietPhieuNhapKhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuNhapKho", Storage="_NhanVien", ThisKey="maNhanVienKeToanKho", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhieuNhapKhos.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhieuNhapKhos.Add(this);
						this._maNhanVienKeToanKho = value.maNhanVien;
					}
					else
					{
						this._maNhanVienKeToanKho = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuNhapKho1", Storage="_NhanVien1", ThisKey="maNhanVienThuKho", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien1
		{
			get
			{
				return this._NhanVien1.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien1.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien1.Entity = null;
						previousValue.PhieuNhapKhos1.Remove(this);
					}
					this._NhanVien1.Entity = value;
					if ((value != null))
					{
						value.PhieuNhapKhos1.Add(this);
						this._maNhanVienThuKho = value.maNhanVien;
					}
					else
					{
						this._maNhanVienThuKho = default(string);
					}
					this.SendPropertyChanged("NhanVien1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_PhieuNhapKho", Storage="_NhaCungCap", ThisKey="maNhaCungCap", OtherKey="maNhaCungCap", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.PhieuNhapKhos.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.PhieuNhapKhos.Add(this);
						this._maNhaCungCap = value.maNhaCungCap;
					}
					else
					{
						this._maNhaCungCap = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhapKho = this;
		}
		
		private void detach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.PhieuNhapKho = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _cMND;
		
		private string _soDienThoai;
		
		private string _eMail;
		
		private string _diaChi;
		
		private string _trangThai;
		
		private string _maLoaiNhanVien;
		
		private EntitySet<PhieuNhapKho> _PhieuNhapKhos;
		
		private EntitySet<PhieuNhapKho> _PhieuNhapKhos1;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
		private EntitySet<DonDatHang> _DonDatHangs1;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
		private EntityRef<LoaiNhanVien> _LoaiNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OncMNDChanging(string value);
    partial void OncMNDChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    partial void OnmaLoaiNhanVienChanging(string value);
    partial void OnmaLoaiNhanVienChanged();
    #endregion
		
		public NhanVien()
		{
			this._PhieuNhapKhos = new EntitySet<PhieuNhapKho>(new Action<PhieuNhapKho>(this.attach_PhieuNhapKhos), new Action<PhieuNhapKho>(this.detach_PhieuNhapKhos));
			this._PhieuNhapKhos1 = new EntitySet<PhieuNhapKho>(new Action<PhieuNhapKho>(this.attach_PhieuNhapKhos1), new Action<PhieuNhapKho>(this.detach_PhieuNhapKhos1));
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			this._DonDatHangs1 = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs1), new Action<DonDatHang>(this.detach_DonDatHangs1));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			this._LoaiNhanVien = default(EntityRef<LoaiNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMND", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string cMND
		{
			get
			{
				return this._cMND;
			}
			set
			{
				if ((this._cMND != value))
				{
					this.OncMNDChanging(value);
					this.SendPropertyChanging();
					this._cMND = value;
					this.SendPropertyChanged("cMND");
					this.OncMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiNhanVien", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maLoaiNhanVien
		{
			get
			{
				return this._maLoaiNhanVien;
			}
			set
			{
				if ((this._maLoaiNhanVien != value))
				{
					if (this._LoaiNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maLoaiNhanVien = value;
					this.SendPropertyChanged("maLoaiNhanVien");
					this.OnmaLoaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuNhapKho", Storage="_PhieuNhapKhos", ThisKey="maNhanVien", OtherKey="maNhanVienKeToanKho")]
		public EntitySet<PhieuNhapKho> PhieuNhapKhos
		{
			get
			{
				return this._PhieuNhapKhos;
			}
			set
			{
				this._PhieuNhapKhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhieuNhapKho1", Storage="_PhieuNhapKhos1", ThisKey="maNhanVien", OtherKey="maNhanVienThuKho")]
		public EntitySet<PhieuNhapKho> PhieuNhapKhos1
		{
			get
			{
				return this._PhieuNhapKhos1;
			}
			set
			{
				this._PhieuNhapKhos1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DonDatHang", Storage="_DonDatHangs", ThisKey="maNhanVien", OtherKey="maNhanVienThuNgan")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DonDatHang1", Storage="_DonDatHangs1", ThisKey="maNhanVien", OtherKey="maNhanVienTuVan")]
		public EntitySet<DonDatHang> DonDatHangs1
		{
			get
			{
				return this._DonDatHangs1;
			}
			set
			{
				this._DonDatHangs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_NhanVien", Storage="_TaiKhoan", ThisKey="maNhanVien", OtherKey="maTaiKhoan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.NhanVien = null;
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.NhanVien = this;
						this._maNhanVien = value.maTaiKhoan;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNhanVien_NhanVien", Storage="_LoaiNhanVien", ThisKey="maLoaiNhanVien", OtherKey="maLoaiNhanVien", IsForeignKey=true)]
		public LoaiNhanVien LoaiNhanVien
		{
			get
			{
				return this._LoaiNhanVien.Entity;
			}
			set
			{
				LoaiNhanVien previousValue = this._LoaiNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._LoaiNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiNhanVien.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._LoaiNhanVien.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._maLoaiNhanVien = value.maLoaiNhanVien;
					}
					else
					{
						this._maLoaiNhanVien = default(string);
					}
					this.SendPropertyChanged("LoaiNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuNhapKhos(PhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhieuNhapKhos(PhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_PhieuNhapKhos1(PhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = this;
		}
		
		private void detach_PhieuNhapKhos1(PhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = null;
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_DonDatHangs1(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = this;
		}
		
		private void detach_DonDatHangs1(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiNhanVien")]
	public partial class LoaiNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoaiNhanVien;
		
		private string _tenLoaiNhanVien;
		
		private string _maPhanQuyen;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiNhanVienChanging(string value);
    partial void OnmaLoaiNhanVienChanged();
    partial void OntenLoaiNhanVienChanging(string value);
    partial void OntenLoaiNhanVienChanged();
    partial void OnmaPhanQuyenChanging(string value);
    partial void OnmaPhanQuyenChanged();
    #endregion
		
		public LoaiNhanVien()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoaiNhanVien", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoaiNhanVien
		{
			get
			{
				return this._maLoaiNhanVien;
			}
			set
			{
				if ((this._maLoaiNhanVien != value))
				{
					this.OnmaLoaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maLoaiNhanVien = value;
					this.SendPropertyChanged("maLoaiNhanVien");
					this.OnmaLoaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoaiNhanVien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenLoaiNhanVien
		{
			get
			{
				return this._tenLoaiNhanVien;
			}
			set
			{
				if ((this._tenLoaiNhanVien != value))
				{
					this.OntenLoaiNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenLoaiNhanVien = value;
					this.SendPropertyChanged("tenLoaiNhanVien");
					this.OntenLoaiNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhanQuyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maPhanQuyen
		{
			get
			{
				return this._maPhanQuyen;
			}
			set
			{
				if ((this._maPhanQuyen != value))
				{
					this.OnmaPhanQuyenChanging(value);
					this.SendPropertyChanging();
					this._maPhanQuyen = value;
					this.SendPropertyChanged("maPhanQuyen");
					this.OnmaPhanQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiNhanVien_NhanVien", Storage="_NhanViens", ThisKey="maLoaiNhanVien", OtherKey="maLoaiNhanVien")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNhanVien = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCungCap")]
	public partial class NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhaCungCap;
		
		private string _tenNhaCungCap;
		
		private string _soDienThoai;
		
		private string _eMail;
		
		private string _quocGia;
		
		private string _diaChi;
		
		private EntitySet<PhieuNhapKho> _PhieuNhapKhos;
		
		private EntitySet<Linhkien> _Linhkiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhaCungCapChanging(string value);
    partial void OnmaNhaCungCapChanged();
    partial void OntenNhaCungCapChanging(string value);
    partial void OntenNhaCungCapChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OnquocGiaChanging(string value);
    partial void OnquocGiaChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    #endregion
		
		public NhaCungCap()
		{
			this._PhieuNhapKhos = new EntitySet<PhieuNhapKho>(new Action<PhieuNhapKho>(this.attach_PhieuNhapKhos), new Action<PhieuNhapKho>(this.detach_PhieuNhapKhos));
			this._Linhkiens = new EntitySet<Linhkien>(new Action<Linhkien>(this.attach_Linhkiens), new Action<Linhkien>(this.detach_Linhkiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhaCungCap", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhaCungCap
		{
			get
			{
				return this._maNhaCungCap;
			}
			set
			{
				if ((this._maNhaCungCap != value))
				{
					this.OnmaNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._maNhaCungCap = value;
					this.SendPropertyChanged("maNhaCungCap");
					this.OnmaNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhaCungCap", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenNhaCungCap
		{
			get
			{
				return this._tenNhaCungCap;
			}
			set
			{
				if ((this._tenNhaCungCap != value))
				{
					this.OntenNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._tenNhaCungCap = value;
					this.SendPropertyChanged("tenNhaCungCap");
					this.OntenNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quocGia", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string quocGia
		{
			get
			{
				return this._quocGia;
			}
			set
			{
				if ((this._quocGia != value))
				{
					this.OnquocGiaChanging(value);
					this.SendPropertyChanging();
					this._quocGia = value;
					this.SendPropertyChanged("quocGia");
					this.OnquocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_PhieuNhapKho", Storage="_PhieuNhapKhos", ThisKey="maNhaCungCap", OtherKey="maNhaCungCap")]
		public EntitySet<PhieuNhapKho> PhieuNhapKhos
		{
			get
			{
				return this._PhieuNhapKhos;
			}
			set
			{
				this._PhieuNhapKhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Linhkien", Storage="_Linhkiens", ThisKey="maNhaCungCap", OtherKey="maNhaCungCap")]
		public EntitySet<Linhkien> Linhkiens
		{
			get
			{
				return this._Linhkiens;
			}
			set
			{
				this._Linhkiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuNhapKhos(PhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_PhieuNhapKhos(PhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
		
		private void attach_Linhkiens(Linhkien entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = this;
		}
		
		private void detach_Linhkiens(Linhkien entity)
		{
			this.SendPropertyChanging();
			entity.NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiLinhKien")]
	public partial class LoaiLinhKien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLoai;
		
		private string _tenLoai;
		
		private EntitySet<Linhkien> _Linhkiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OntenLoaiChanging(string value);
    partial void OntenLoaiChanged();
    #endregion
		
		public LoaiLinhKien()
		{
			this._Linhkiens = new EntitySet<Linhkien>(new Action<Linhkien>(this.attach_Linhkiens), new Action<Linhkien>(this.detach_Linhkiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLoai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenLoai
		{
			get
			{
				return this._tenLoai;
			}
			set
			{
				if ((this._tenLoai != value))
				{
					this.OntenLoaiChanging(value);
					this.SendPropertyChanging();
					this._tenLoai = value;
					this.SendPropertyChanged("tenLoai");
					this.OntenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiLinhKien_Linhkien", Storage="_Linhkiens", ThisKey="maLoai", OtherKey="maLoai")]
		public EntitySet<Linhkien> Linhkiens
		{
			get
			{
				return this._Linhkiens;
			}
			set
			{
				this._Linhkiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Linhkiens(Linhkien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiLinhKien = this;
		}
		
		private void detach_Linhkiens(Linhkien entity)
		{
			this.SendPropertyChanging();
			entity.LoaiLinhKien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Linhkien")]
	public partial class Linhkien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLinhKien;
		
		private string _tenLinhKien;
		
		private string _maLoai;
		
		private double _giaMua;
		
		private double _giaBan;
		
		private int _soLuong;
		
		private double _mucGiamGia;
		
		private string _maNhaCungCap;
		
		private EntitySet<ChiTietPhieuNhapKho> _ChiTietPhieuNhapKhos;
		
		private EntitySet<ChiTietDonDatHang> _ChiTietDonDatHangs;
		
		private EntityRef<LoaiLinhKien> _LoaiLinhKien;
		
		private EntityRef<NhaCungCap> _NhaCungCap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLinhKienChanging(string value);
    partial void OnmaLinhKienChanged();
    partial void OntenLinhKienChanging(string value);
    partial void OntenLinhKienChanged();
    partial void OnmaLoaiChanging(string value);
    partial void OnmaLoaiChanged();
    partial void OngiaMuaChanging(double value);
    partial void OngiaMuaChanged();
    partial void OngiaBanChanging(double value);
    partial void OngiaBanChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    partial void OnmucGiamGiaChanging(double value);
    partial void OnmucGiamGiaChanged();
    partial void OnmaNhaCungCapChanging(string value);
    partial void OnmaNhaCungCapChanged();
    #endregion
		
		public Linhkien()
		{
			this._ChiTietPhieuNhapKhos = new EntitySet<ChiTietPhieuNhapKho>(new Action<ChiTietPhieuNhapKho>(this.attach_ChiTietPhieuNhapKhos), new Action<ChiTietPhieuNhapKho>(this.detach_ChiTietPhieuNhapKhos));
			this._ChiTietDonDatHangs = new EntitySet<ChiTietDonDatHang>(new Action<ChiTietDonDatHang>(this.attach_ChiTietDonDatHangs), new Action<ChiTietDonDatHang>(this.detach_ChiTietDonDatHangs));
			this._LoaiLinhKien = default(EntityRef<LoaiLinhKien>);
			this._NhaCungCap = default(EntityRef<NhaCungCap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLinhKien", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLinhKien
		{
			get
			{
				return this._maLinhKien;
			}
			set
			{
				if ((this._maLinhKien != value))
				{
					this.OnmaLinhKienChanging(value);
					this.SendPropertyChanging();
					this._maLinhKien = value;
					this.SendPropertyChanged("maLinhKien");
					this.OnmaLinhKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLinhKien", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string tenLinhKien
		{
			get
			{
				return this._tenLinhKien;
			}
			set
			{
				if ((this._tenLinhKien != value))
				{
					this.OntenLinhKienChanging(value);
					this.SendPropertyChanging();
					this._tenLinhKien = value;
					this.SendPropertyChanged("tenLinhKien");
					this.OntenLinhKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLoai", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maLoai
		{
			get
			{
				return this._maLoai;
			}
			set
			{
				if ((this._maLoai != value))
				{
					if (this._LoaiLinhKien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLoaiChanging(value);
					this.SendPropertyChanging();
					this._maLoai = value;
					this.SendPropertyChanged("maLoai");
					this.OnmaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaMua", DbType="Float NOT NULL")]
		public double giaMua
		{
			get
			{
				return this._giaMua;
			}
			set
			{
				if ((this._giaMua != value))
				{
					this.OngiaMuaChanging(value);
					this.SendPropertyChanging();
					this._giaMua = value;
					this.SendPropertyChanged("giaMua");
					this.OngiaMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float NOT NULL")]
		public double giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucGiamGia", DbType="Float NOT NULL")]
		public double mucGiamGia
		{
			get
			{
				return this._mucGiamGia;
			}
			set
			{
				if ((this._mucGiamGia != value))
				{
					this.OnmucGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._mucGiamGia = value;
					this.SendPropertyChanged("mucGiamGia");
					this.OnmucGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhaCungCap", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maNhaCungCap
		{
			get
			{
				return this._maNhaCungCap;
			}
			set
			{
				if ((this._maNhaCungCap != value))
				{
					if (this._NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._maNhaCungCap = value;
					this.SendPropertyChanged("maNhaCungCap");
					this.OnmaNhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linhkien_ChiTietPhieuNhapKho", Storage="_ChiTietPhieuNhapKhos", ThisKey="maLinhKien", OtherKey="maLinhKien")]
		public EntitySet<ChiTietPhieuNhapKho> ChiTietPhieuNhapKhos
		{
			get
			{
				return this._ChiTietPhieuNhapKhos;
			}
			set
			{
				this._ChiTietPhieuNhapKhos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linhkien_ChiTietDonDatHang", Storage="_ChiTietDonDatHangs", ThisKey="maLinhKien", OtherKey="maLinhKien")]
		public EntitySet<ChiTietDonDatHang> ChiTietDonDatHangs
		{
			get
			{
				return this._ChiTietDonDatHangs;
			}
			set
			{
				this._ChiTietDonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiLinhKien_Linhkien", Storage="_LoaiLinhKien", ThisKey="maLoai", OtherKey="maLoai", IsForeignKey=true)]
		public LoaiLinhKien LoaiLinhKien
		{
			get
			{
				return this._LoaiLinhKien.Entity;
			}
			set
			{
				LoaiLinhKien previousValue = this._LoaiLinhKien.Entity;
				if (((previousValue != value) 
							|| (this._LoaiLinhKien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiLinhKien.Entity = null;
						previousValue.Linhkiens.Remove(this);
					}
					this._LoaiLinhKien.Entity = value;
					if ((value != null))
					{
						value.Linhkiens.Add(this);
						this._maLoai = value.maLoai;
					}
					else
					{
						this._maLoai = default(string);
					}
					this.SendPropertyChanged("LoaiLinhKien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaCungCap_Linhkien", Storage="_NhaCungCap", ThisKey="maNhaCungCap", OtherKey="maNhaCungCap", IsForeignKey=true)]
		public NhaCungCap NhaCungCap
		{
			get
			{
				return this._NhaCungCap.Entity;
			}
			set
			{
				NhaCungCap previousValue = this._NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaCungCap.Entity = null;
						previousValue.Linhkiens.Remove(this);
					}
					this._NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.Linhkiens.Add(this);
						this._maNhaCungCap = value.maNhaCungCap;
					}
					else
					{
						this._maNhaCungCap = default(string);
					}
					this.SendPropertyChanged("NhaCungCap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.Linhkien = this;
		}
		
		private void detach_ChiTietPhieuNhapKhos(ChiTietPhieuNhapKho entity)
		{
			this.SendPropertyChanging();
			entity.Linhkien = null;
		}
		
		private void attach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.Linhkien = this;
		}
		
		private void detach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.Linhkien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhachHang;
		
		private string _tenKhachHang;
		
		private string _soDienThoai;
		
		private string _eMail;
		
		private string _diaChi;
		
		private EntitySet<DonDatHang> _DonDatHangs;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OntenKhachHangChanging(string value);
    partial void OntenKhachHangChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    #endregion
		
		public KhachHang()
		{
			this._DonDatHangs = new EntitySet<DonDatHang>(new Action<DonDatHang>(this.attach_DonDatHangs), new Action<DonDatHang>(this.detach_DonDatHangs));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhachHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenKhachHang
		{
			get
			{
				return this._tenKhachHang;
			}
			set
			{
				if ((this._tenKhachHang != value))
				{
					this.OntenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._tenKhachHang = value;
					this.SendPropertyChanged("tenKhachHang");
					this.OntenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_DonDatHangs", ThisKey="maKhachHang", OtherKey="maKhachHang")]
		public EntitySet<DonDatHang> DonDatHangs
		{
			get
			{
				return this._DonDatHangs;
			}
			set
			{
				this._DonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_KhachHang", Storage="_TaiKhoan", ThisKey="maKhachHang", OtherKey="maTaiKhoan", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.KhachHang = null;
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.KhachHang = this;
						this._maKhachHang = value.maTaiKhoan;
					}
					else
					{
						this._maKhachHang = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DonDatHangs(DonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonDatHang")]
	public partial class DonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDonDatHang;
		
		private string _maKhachHang;
		
		private string _maNhanVienThuNgan;
		
		private string _maNhanVienTuVan;
		
		private System.DateTime _ngayLap;
		
		private double _tongTien;
		
		private string _noiNhanHang;
		
		private string _trangThai;
		
		private EntitySet<ChiTietDonDatHang> _ChiTietDonDatHangs;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<NhanVien> _NhanVien1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDonDatHangChanging(string value);
    partial void OnmaDonDatHangChanged();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OnmaNhanVienThuNganChanging(string value);
    partial void OnmaNhanVienThuNganChanged();
    partial void OnmaNhanVienTuVanChanging(string value);
    partial void OnmaNhanVienTuVanChanged();
    partial void OnngayLapChanging(System.DateTime value);
    partial void OnngayLapChanged();
    partial void OntongTienChanging(double value);
    partial void OntongTienChanged();
    partial void OnnoiNhanHangChanging(string value);
    partial void OnnoiNhanHangChanged();
    partial void OntrangThaiChanging(string value);
    partial void OntrangThaiChanged();
    #endregion
		
		public DonDatHang()
		{
			this._ChiTietDonDatHangs = new EntitySet<ChiTietDonDatHang>(new Action<ChiTietDonDatHang>(this.attach_ChiTietDonDatHangs), new Action<ChiTietDonDatHang>(this.detach_ChiTietDonDatHangs));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanVien = default(EntityRef<NhanVien>);
			this._NhanVien1 = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDonDatHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDonDatHang
		{
			get
			{
				return this._maDonDatHang;
			}
			set
			{
				if ((this._maDonDatHang != value))
				{
					this.OnmaDonDatHangChanging(value);
					this.SendPropertyChanging();
					this._maDonDatHang = value;
					this.SendPropertyChanged("maDonDatHang");
					this.OnmaDonDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVienThuNgan", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maNhanVienThuNgan
		{
			get
			{
				return this._maNhanVienThuNgan;
			}
			set
			{
				if ((this._maNhanVienThuNgan != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienThuNganChanging(value);
					this.SendPropertyChanging();
					this._maNhanVienThuNgan = value;
					this.SendPropertyChanged("maNhanVienThuNgan");
					this.OnmaNhanVienThuNganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVienTuVan", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maNhanVienTuVan
		{
			get
			{
				return this._maNhanVienTuVan;
			}
			set
			{
				if ((this._maNhanVienTuVan != value))
				{
					if (this._NhanVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienTuVanChanging(value);
					this.SendPropertyChanging();
					this._maNhanVienTuVan = value;
					this.SendPropertyChanged("maNhanVienTuVan");
					this.OnmaNhanVienTuVanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayLap", DbType="Date NOT NULL")]
		public System.DateTime ngayLap
		{
			get
			{
				return this._ngayLap;
			}
			set
			{
				if ((this._ngayLap != value))
				{
					this.OnngayLapChanging(value);
					this.SendPropertyChanging();
					this._ngayLap = value;
					this.SendPropertyChanged("ngayLap");
					this.OnngayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongTien", DbType="Float NOT NULL")]
		public double tongTien
		{
			get
			{
				return this._tongTien;
			}
			set
			{
				if ((this._tongTien != value))
				{
					this.OntongTienChanging(value);
					this.SendPropertyChanging();
					this._tongTien = value;
					this.SendPropertyChanged("tongTien");
					this.OntongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiNhanHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string noiNhanHang
		{
			get
			{
				return this._noiNhanHang;
			}
			set
			{
				if ((this._noiNhanHang != value))
				{
					this.OnnoiNhanHangChanging(value);
					this.SendPropertyChanging();
					this._noiNhanHang = value;
					this.SendPropertyChanged("noiNhanHang");
					this.OnnoiNhanHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThai", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string trangThai
		{
			get
			{
				return this._trangThai;
			}
			set
			{
				if ((this._trangThai != value))
				{
					this.OntrangThaiChanging(value);
					this.SendPropertyChanging();
					this._trangThai = value;
					this.SendPropertyChanged("trangThai");
					this.OntrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_ChiTietDonDatHang", Storage="_ChiTietDonDatHangs", ThisKey="maDonDatHang", OtherKey="maDonDatHang")]
		public EntitySet<ChiTietDonDatHang> ChiTietDonDatHangs
		{
			get
			{
				return this._ChiTietDonDatHangs;
			}
			set
			{
				this._ChiTietDonDatHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DonDatHang", Storage="_KhachHang", ThisKey="maKhachHang", OtherKey="maKhachHang", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._maKhachHang = value.maKhachHang;
					}
					else
					{
						this._maKhachHang = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DonDatHang", Storage="_NhanVien", ThisKey="maNhanVienThuNgan", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.DonDatHangs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs.Add(this);
						this._maNhanVienThuNgan = value.maNhanVien;
					}
					else
					{
						this._maNhanVienThuNgan = default(string);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DonDatHang1", Storage="_NhanVien1", ThisKey="maNhanVienTuVan", OtherKey="maNhanVien", IsForeignKey=true)]
		public NhanVien NhanVien1
		{
			get
			{
				return this._NhanVien1.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien1.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien1.Entity = null;
						previousValue.DonDatHangs1.Remove(this);
					}
					this._NhanVien1.Entity = value;
					if ((value != null))
					{
						value.DonDatHangs1.Add(this);
						this._maNhanVienTuVan = value.maNhanVien;
					}
					else
					{
						this._maNhanVienTuVan = default(string);
					}
					this.SendPropertyChanged("NhanVien1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = this;
		}
		
		private void detach_ChiTietDonDatHangs(ChiTietDonDatHang entity)
		{
			this.SendPropertyChanging();
			entity.DonDatHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietPhieuNhapKho")]
	public partial class ChiTietPhieuNhapKho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maPhieuNhapKho;
		
		private string _maLinhKien;
		
		private int _soLuong;
		
		private double _giaMua;
		
		private double _thanhTien;
		
		private EntityRef<Linhkien> _Linhkien;
		
		private EntityRef<PhieuNhapKho> _PhieuNhapKho;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaPhieuNhapKhoChanging(string value);
    partial void OnmaPhieuNhapKhoChanged();
    partial void OnmaLinhKienChanging(string value);
    partial void OnmaLinhKienChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    partial void OngiaMuaChanging(double value);
    partial void OngiaMuaChanged();
    partial void OnthanhTienChanging(double value);
    partial void OnthanhTienChanged();
    #endregion
		
		public ChiTietPhieuNhapKho()
		{
			this._Linhkien = default(EntityRef<Linhkien>);
			this._PhieuNhapKho = default(EntityRef<PhieuNhapKho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maPhieuNhapKho", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maPhieuNhapKho
		{
			get
			{
				return this._maPhieuNhapKho;
			}
			set
			{
				if ((this._maPhieuNhapKho != value))
				{
					if (this._PhieuNhapKho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaPhieuNhapKhoChanging(value);
					this.SendPropertyChanging();
					this._maPhieuNhapKho = value;
					this.SendPropertyChanged("maPhieuNhapKho");
					this.OnmaPhieuNhapKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLinhKien", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLinhKien
		{
			get
			{
				return this._maLinhKien;
			}
			set
			{
				if ((this._maLinhKien != value))
				{
					if (this._Linhkien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLinhKienChanging(value);
					this.SendPropertyChanging();
					this._maLinhKien = value;
					this.SendPropertyChanged("maLinhKien");
					this.OnmaLinhKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaMua", DbType="Float NOT NULL")]
		public double giaMua
		{
			get
			{
				return this._giaMua;
			}
			set
			{
				if ((this._giaMua != value))
				{
					this.OngiaMuaChanging(value);
					this.SendPropertyChanging();
					this._giaMua = value;
					this.SendPropertyChanged("giaMua");
					this.OngiaMuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Float NOT NULL")]
		public double thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linhkien_ChiTietPhieuNhapKho", Storage="_Linhkien", ThisKey="maLinhKien", OtherKey="maLinhKien", IsForeignKey=true)]
		public Linhkien Linhkien
		{
			get
			{
				return this._Linhkien.Entity;
			}
			set
			{
				Linhkien previousValue = this._Linhkien.Entity;
				if (((previousValue != value) 
							|| (this._Linhkien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Linhkien.Entity = null;
						previousValue.ChiTietPhieuNhapKhos.Remove(this);
					}
					this._Linhkien.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhapKhos.Add(this);
						this._maLinhKien = value.maLinhKien;
					}
					else
					{
						this._maLinhKien = default(string);
					}
					this.SendPropertyChanged("Linhkien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuNhapKho_ChiTietPhieuNhapKho", Storage="_PhieuNhapKho", ThisKey="maPhieuNhapKho", OtherKey="maPhieuNhapKho", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public PhieuNhapKho PhieuNhapKho
		{
			get
			{
				return this._PhieuNhapKho.Entity;
			}
			set
			{
				PhieuNhapKho previousValue = this._PhieuNhapKho.Entity;
				if (((previousValue != value) 
							|| (this._PhieuNhapKho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuNhapKho.Entity = null;
						previousValue.ChiTietPhieuNhapKhos.Remove(this);
					}
					this._PhieuNhapKho.Entity = value;
					if ((value != null))
					{
						value.ChiTietPhieuNhapKhos.Add(this);
						this._maPhieuNhapKho = value.maPhieuNhapKho;
					}
					else
					{
						this._maPhieuNhapKho = default(string);
					}
					this.SendPropertyChanged("PhieuNhapKho");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietDonDatHang")]
	public partial class ChiTietDonDatHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDonDatHang;
		
		private string _maLinhKien;
		
		private int _soLuong;
		
		private double _giaBan;
		
		private double _mucGiamGia;
		
		private double _thanhTien;
		
		private EntityRef<DonDatHang> _DonDatHang;
		
		private EntityRef<Linhkien> _Linhkien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDonDatHangChanging(string value);
    partial void OnmaDonDatHangChanged();
    partial void OnmaLinhKienChanging(string value);
    partial void OnmaLinhKienChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    partial void OngiaBanChanging(double value);
    partial void OngiaBanChanged();
    partial void OnmucGiamGiaChanging(double value);
    partial void OnmucGiamGiaChanged();
    partial void OnthanhTienChanging(double value);
    partial void OnthanhTienChanged();
    #endregion
		
		public ChiTietDonDatHang()
		{
			this._DonDatHang = default(EntityRef<DonDatHang>);
			this._Linhkien = default(EntityRef<Linhkien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDonDatHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maDonDatHang
		{
			get
			{
				return this._maDonDatHang;
			}
			set
			{
				if ((this._maDonDatHang != value))
				{
					if (this._DonDatHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDonDatHangChanging(value);
					this.SendPropertyChanging();
					this._maDonDatHang = value;
					this.SendPropertyChanged("maDonDatHang");
					this.OnmaDonDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLinhKien", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLinhKien
		{
			get
			{
				return this._maLinhKien;
			}
			set
			{
				if ((this._maLinhKien != value))
				{
					if (this._Linhkien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLinhKienChanging(value);
					this.SendPropertyChanging();
					this._maLinhKien = value;
					this.SendPropertyChanged("maLinhKien");
					this.OnmaLinhKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float NOT NULL")]
		public double giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucGiamGia", DbType="Float NOT NULL")]
		public double mucGiamGia
		{
			get
			{
				return this._mucGiamGia;
			}
			set
			{
				if ((this._mucGiamGia != value))
				{
					this.OnmucGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._mucGiamGia = value;
					this.SendPropertyChanged("mucGiamGia");
					this.OnmucGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhTien", DbType="Float NOT NULL")]
		public double thanhTien
		{
			get
			{
				return this._thanhTien;
			}
			set
			{
				if ((this._thanhTien != value))
				{
					this.OnthanhTienChanging(value);
					this.SendPropertyChanging();
					this._thanhTien = value;
					this.SendPropertyChanged("thanhTien");
					this.OnthanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonDatHang_ChiTietDonDatHang", Storage="_DonDatHang", ThisKey="maDonDatHang", OtherKey="maDonDatHang", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public DonDatHang DonDatHang
		{
			get
			{
				return this._DonDatHang.Entity;
			}
			set
			{
				DonDatHang previousValue = this._DonDatHang.Entity;
				if (((previousValue != value) 
							|| (this._DonDatHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonDatHang.Entity = null;
						previousValue.ChiTietDonDatHangs.Remove(this);
					}
					this._DonDatHang.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonDatHangs.Add(this);
						this._maDonDatHang = value.maDonDatHang;
					}
					else
					{
						this._maDonDatHang = default(string);
					}
					this.SendPropertyChanged("DonDatHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Linhkien_ChiTietDonDatHang", Storage="_Linhkien", ThisKey="maLinhKien", OtherKey="maLinhKien", IsForeignKey=true)]
		public Linhkien Linhkien
		{
			get
			{
				return this._Linhkien.Entity;
			}
			set
			{
				Linhkien previousValue = this._Linhkien.Entity;
				if (((previousValue != value) 
							|| (this._Linhkien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Linhkien.Entity = null;
						previousValue.ChiTietDonDatHangs.Remove(this);
					}
					this._Linhkien.Entity = value;
					if ((value != null))
					{
						value.ChiTietDonDatHangs.Add(this);
						this._maLinhKien = value.maLinhKien;
					}
					else
					{
						this._maLinhKien = default(string);
					}
					this.SendPropertyChanged("Linhkien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
