#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyLinhKien")]
	public partial class DataQuanLyLinhKienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
    partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
    partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
    partial void InsertnhanVien(nhanVien instance);
    partial void UpdatenhanVien(nhanVien instance);
    partial void DeletenhanVien(nhanVien instance);
    partial void InserthangHoa(hangHoa instance);
    partial void UpdatehangHoa(hangHoa instance);
    partial void DeletehangHoa(hangHoa instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertkhachHang(khachHang instance);
    partial void UpdatekhachHang(khachHang instance);
    partial void DeletekhachHang(khachHang instance);
    #endregion
		
		public DataQuanLyLinhKienDataContext() : 
				base(global::DLL.Properties.Settings.Default.QuanLyLinhKienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataQuanLyLinhKienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this.GetTable<ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<nhanVien> nhanViens
		{
			get
			{
				return this.GetTable<nhanVien>();
			}
		}
		
		public System.Data.Linq.Table<hangHoa> hangHoas
		{
			get
			{
				return this.GetTable<hangHoa>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<khachHang> khachHangs
		{
			get
			{
				return this.GetTable<khachHang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
	public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHoaDon;
		
		private string _maHang;
		
		private int _soLuong;
		
		private double _giaBan;
		
		private double _mucGiamGia;
		
		private EntityRef<hangHoa> _hangHoa;
		
		private EntityRef<HoaDon> _HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHoaDonChanging(string value);
    partial void OnmaHoaDonChanged();
    partial void OnmaHangChanging(string value);
    partial void OnmaHangChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    partial void OngiaBanChanging(double value);
    partial void OngiaBanChanged();
    partial void OnmucGiamGiaChanging(double value);
    partial void OnmucGiamGiaChanged();
    #endregion
		
		public ChiTietHoaDon()
		{
			this._hangHoa = default(EntityRef<hangHoa>);
			this._HoaDon = default(EntityRef<HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHang
		{
			get
			{
				return this._maHang;
			}
			set
			{
				if ((this._maHang != value))
				{
					if (this._hangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHangChanging(value);
					this.SendPropertyChanging();
					this._maHang = value;
					this.SendPropertyChanged("maHang");
					this.OnmaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float NOT NULL")]
		public double giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mucGiamGia", DbType="Float NOT NULL")]
		public double mucGiamGia
		{
			get
			{
				return this._mucGiamGia;
			}
			set
			{
				if ((this._mucGiamGia != value))
				{
					this.OnmucGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._mucGiamGia = value;
					this.SendPropertyChanged("mucGiamGia");
					this.OnmucGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hangHoa_ChiTietHoaDon", Storage="_hangHoa", ThisKey="maHang", OtherKey="maHang", IsForeignKey=true)]
		public hangHoa hangHoa
		{
			get
			{
				return this._hangHoa.Entity;
			}
			set
			{
				hangHoa previousValue = this._hangHoa.Entity;
				if (((previousValue != value) 
							|| (this._hangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hangHoa.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._hangHoa.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._maHang = value.maHang;
					}
					else
					{
						this._maHang = default(string);
					}
					this.SendPropertyChanged("hangHoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_HoaDon", ThisKey="maHoaDon", OtherKey="maHoaDon", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ChiTietHoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ChiTietHoaDons.Add(this);
						this._maHoaDon = value.maHoaDon;
					}
					else
					{
						this._maHoaDon = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanVien")]
	public partial class nhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNhanVien;
		
		private string _tenNhanVien;
		
		private string _cMND;
		
		private string _soDienThoai;
		
		private string _diaChi;
		
		private string _eMail;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OntenNhanVienChanging(string value);
    partial void OntenNhanVienChanged();
    partial void OncMNDChanging(string value);
    partial void OncMNDChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    #endregion
		
		public nhanVien()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNhanVien", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string tenNhanVien
		{
			get
			{
				return this._tenNhanVien;
			}
			set
			{
				if ((this._tenNhanVien != value))
				{
					this.OntenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._tenNhanVien = value;
					this.SendPropertyChanged("tenNhanVien");
					this.OntenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cMND", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string cMND
		{
			get
			{
				return this._cMND;
			}
			set
			{
				if ((this._cMND != value))
				{
					this.OncMNDChanging(value);
					this.SendPropertyChanging();
					this._cMND = value;
					this.SendPropertyChanged("cMND");
					this.OncMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_HoaDon", Storage="_HoaDons", ThisKey="maNhanVien", OtherKey="maNhanVien")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.nhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hangHoa")]
	public partial class hangHoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHang;
		
		private string _tenHang;
		
		private string _loaiHang;
		
		private double _giaBan;
		
		private int _soLuong;
		
		private string _nhaCungCap;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHangChanging(string value);
    partial void OnmaHangChanged();
    partial void OntenHangChanging(string value);
    partial void OntenHangChanged();
    partial void OnloaiHangChanging(string value);
    partial void OnloaiHangChanged();
    partial void OngiaBanChanging(double value);
    partial void OngiaBanChanged();
    partial void OnsoLuongChanging(int value);
    partial void OnsoLuongChanged();
    partial void OnnhaCungCapChanging(string value);
    partial void OnnhaCungCapChanged();
    #endregion
		
		public hangHoa()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHang
		{
			get
			{
				return this._maHang;
			}
			set
			{
				if ((this._maHang != value))
				{
					this.OnmaHangChanging(value);
					this.SendPropertyChanging();
					this._maHang = value;
					this.SendPropertyChanged("maHang");
					this.OnmaHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tenHang
		{
			get
			{
				return this._tenHang;
			}
			set
			{
				if ((this._tenHang != value))
				{
					this.OntenHangChanging(value);
					this.SendPropertyChanging();
					this._tenHang = value;
					this.SendPropertyChanged("tenHang");
					this.OntenHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string loaiHang
		{
			get
			{
				return this._loaiHang;
			}
			set
			{
				if ((this._loaiHang != value))
				{
					this.OnloaiHangChanging(value);
					this.SendPropertyChanging();
					this._loaiHang = value;
					this.SendPropertyChanged("loaiHang");
					this.OnloaiHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaBan", DbType="Float NOT NULL")]
		public double giaBan
		{
			get
			{
				return this._giaBan;
			}
			set
			{
				if ((this._giaBan != value))
				{
					this.OngiaBanChanging(value);
					this.SendPropertyChanging();
					this._giaBan = value;
					this.SendPropertyChanged("giaBan");
					this.OngiaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int NOT NULL")]
		public int soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhaCungCap", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string nhaCungCap
		{
			get
			{
				return this._nhaCungCap;
			}
			set
			{
				if ((this._nhaCungCap != value))
				{
					this.OnnhaCungCapChanging(value);
					this.SendPropertyChanging();
					this._nhaCungCap = value;
					this.SendPropertyChanged("nhaCungCap");
					this.OnnhaCungCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hangHoa_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="maHang", OtherKey="maHang")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.hangHoa = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.hangHoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHoaDon;
		
		private string _maKhachHang;
		
		private string _maNhanVien;
		
		private System.DateTime _ngayDatHang;
		
		private System.DateTime _ngayGiaoHang;
		
		private string _noiNhanHang;
		
		private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
		
		private EntityRef<nhanVien> _nhanVien;
		
		private EntityRef<khachHang> _khachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHoaDonChanging(string value);
    partial void OnmaHoaDonChanged();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OnmaNhanVienChanging(string value);
    partial void OnmaNhanVienChanged();
    partial void OnngayDatHangChanging(System.DateTime value);
    partial void OnngayDatHangChanged();
    partial void OnngayGiaoHangChanging(System.DateTime value);
    partial void OnngayGiaoHangChanged();
    partial void OnnoiNhanHangChanging(string value);
    partial void OnnoiNhanHangChanged();
    #endregion
		
		public HoaDon()
		{
			this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
			this._nhanVien = default(EntityRef<nhanVien>);
			this._khachHang = default(EntityRef<khachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHoaDon", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHoaDon
		{
			get
			{
				return this._maHoaDon;
			}
			set
			{
				if ((this._maHoaDon != value))
				{
					this.OnmaHoaDonChanging(value);
					this.SendPropertyChanging();
					this._maHoaDon = value;
					this.SendPropertyChanged("maHoaDon");
					this.OnmaHoaDonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					if (this._khachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNhanVien", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string maNhanVien
		{
			get
			{
				return this._maNhanVien;
			}
			set
			{
				if ((this._maNhanVien != value))
				{
					if (this._nhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._maNhanVien = value;
					this.SendPropertyChanged("maNhanVien");
					this.OnmaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDatHang", DbType="Date NOT NULL")]
		public System.DateTime ngayDatHang
		{
			get
			{
				return this._ngayDatHang;
			}
			set
			{
				if ((this._ngayDatHang != value))
				{
					this.OnngayDatHangChanging(value);
					this.SendPropertyChanging();
					this._ngayDatHang = value;
					this.SendPropertyChanged("ngayDatHang");
					this.OnngayDatHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayGiaoHang", DbType="Date NOT NULL")]
		public System.DateTime ngayGiaoHang
		{
			get
			{
				return this._ngayGiaoHang;
			}
			set
			{
				if ((this._ngayGiaoHang != value))
				{
					this.OnngayGiaoHangChanging(value);
					this.SendPropertyChanging();
					this._ngayGiaoHang = value;
					this.SendPropertyChanged("ngayGiaoHang");
					this.OnngayGiaoHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noiNhanHang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string noiNhanHang
		{
			get
			{
				return this._noiNhanHang;
			}
			set
			{
				if ((this._noiNhanHang != value))
				{
					this.OnnoiNhanHangChanging(value);
					this.SendPropertyChanging();
					this._noiNhanHang = value;
					this.SendPropertyChanged("noiNhanHang");
					this.OnnoiNhanHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="maHoaDon", OtherKey="maHoaDon")]
		public EntitySet<ChiTietHoaDon> ChiTietHoaDons
		{
			get
			{
				return this._ChiTietHoaDons;
			}
			set
			{
				this._ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanVien_HoaDon", Storage="_nhanVien", ThisKey="maNhanVien", OtherKey="maNhanVien", IsForeignKey=true)]
		public nhanVien nhanVien
		{
			get
			{
				return this._nhanVien.Entity;
			}
			set
			{
				nhanVien previousValue = this._nhanVien.Entity;
				if (((previousValue != value) 
							|| (this._nhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._nhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maNhanVien = value.maNhanVien;
					}
					else
					{
						this._maNhanVien = default(string);
					}
					this.SendPropertyChanged("nhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_HoaDon", Storage="_khachHang", ThisKey="maKhachHang", OtherKey="maKhachHang", IsForeignKey=true)]
		public khachHang khachHang
		{
			get
			{
				return this._khachHang.Entity;
			}
			set
			{
				khachHang previousValue = this._khachHang.Entity;
				if (((previousValue != value) 
							|| (this._khachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._khachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maKhachHang = value.maKhachHang;
					}
					else
					{
						this._maKhachHang = default(string);
					}
					this.SendPropertyChanged("khachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachHang")]
	public partial class khachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKhachHang;
		
		private string _tenKhachHang;
		
		private string _soDienThoai;
		
		private string _diaChi;
		
		private string _eMail;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKhachHangChanging(string value);
    partial void OnmaKhachHangChanged();
    partial void OntenKhachHangChanging(string value);
    partial void OntenKhachHangChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OneMailChanging(string value);
    partial void OneMailChanged();
    #endregion
		
		public khachHang()
		{
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKhachHang", DbType="NVarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKhachHang
		{
			get
			{
				return this._maKhachHang;
			}
			set
			{
				if ((this._maKhachHang != value))
				{
					this.OnmaKhachHangChanging(value);
					this.SendPropertyChanging();
					this._maKhachHang = value;
					this.SendPropertyChanged("maKhachHang");
					this.OnmaKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKhachHang", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string tenKhachHang
		{
			get
			{
				return this._tenKhachHang;
			}
			set
			{
				if ((this._tenKhachHang != value))
				{
					this.OntenKhachHangChanging(value);
					this.SendPropertyChanging();
					this._tenKhachHang = value;
					this.SendPropertyChanged("tenKhachHang");
					this.OntenKhachHangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eMail", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string eMail
		{
			get
			{
				return this._eMail;
			}
			set
			{
				if ((this._eMail != value))
				{
					this.OneMailChanging(value);
					this.SendPropertyChanging();
					this._eMail = value;
					this.SendPropertyChanged("eMail");
					this.OneMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachHang_HoaDon", Storage="_HoaDons", ThisKey="maKhachHang", OtherKey="maKhachHang")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.khachHang = null;
		}
	}
}
#pragma warning restore 1591
